
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mainstack
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: